# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('report_id', models.CharField(blank=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('idcard', models.CharField(blank=True, max_length=64, null=True)),
                ('report_type', models.CharField(blank=True, max_length=16, null=True)),
                ('report_datail', models.TextField(blank=True, null=True)),
                ('create_time', models.IntegerField()),
            ],
            options={
                'db_table': 'report_record',
                'managed': False,
            },
        ),
    ]
