# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField(db_index=True)),
                ('report_id', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('idcard', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('create_time', models.IntegerField()),
            ],
            options={
                'db_table': 'report_history',
                'managed': False,
            },
        ),
    ]
