# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('name', models.CharField(max_length=64, verbose_name='\u59d3\u540d')),
                ('idcard', models.CharField(max_length=64, verbose_name='\u8eab\u4efd\u8bc1\u53f7')),
                ('phone', models.CharField(max_length=64, verbose_name='\u624b\u673a\u53f7')),
                ('sex', models.CharField(max_length=8, verbose_name='\u6027\u522b')),
                ('native_place', models.CharField(max_length=256, verbose_name='\u7c4d\u8d2f')),
                ('education', models.CharField(max_length=256, verbose_name='\u6559\u80b2\u7a0b\u5ea6')),
                ('jobs', models.CharField(max_length=256, verbose_name='\u804c\u4e1a')),
                ('live_place', models.CharField(max_length=256, verbose_name='\u5c45\u4f4f\u5730')),
                ('application_place', models.CharField(max_length=256, verbose_name='\u7533\u8bf7\u5730')),
                ('application_time', models.CharField(max_length=32, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('create_time', models.IntegerField()),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
