# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20180126_1616'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfoforstatistics',
            table=None,
        ),
    ]
