# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0005_auto_20180126_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='application_time',
            field=models.DateTimeField(db_index=True, max_length=32, verbose_name='\u7533\u8bf7\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
