# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0006_auto_20180130_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='application_place',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='live_place',
        ),
        migrations.RemoveField(
            model_name='userinfoforstatistics',
            name='native_place',
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='application_address',
            field=models.CharField(default='', max_length=256, verbose_name='\u7533\u8bf7\u5730\u8be6\u7ec6\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='application_city',
            field=models.CharField(default='', max_length=128, validators='\u7533\u8bf7\u5730\u5e02'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='application_district',
            field=models.CharField(default='', max_length=128, validators='\u7533\u8bf7\u5730\u533a'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='application_province',
            field=models.CharField(default='', max_length=128, validators='\u7533\u8bf7\u5730\u7701'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='live_address',
            field=models.CharField(default='', max_length=256, verbose_name='\u5c45\u4f4f\u5730\u8be6\u7ec6\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='live_city',
            field=models.CharField(default='', max_length=128, validators='\u5c45\u4f4f\u5730\u5e02'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='live_district',
            field=models.CharField(default='', max_length=128, validators='\u5c45\u4f4f\u5730\u533a'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='live_province',
            field=models.CharField(default='', max_length=128, validators='\u5c45\u4f4f\u5730\u7701'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='native_address',
            field=models.CharField(default='', max_length=256, verbose_name='\u7c4d\u8d2f\u8be6\u7ec6\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='native_city',
            field=models.CharField(default='', max_length=128, validators='\u7c4d\u8d2f\u5e02'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='native_district',
            field=models.CharField(default='', max_length=128, validators='\u7c4d\u8d2f\u533a'),
        ),
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='native_province',
            field=models.CharField(default='', max_length=128, validators='\u7c4d\u8d2f\u7701'),
        ),
    ]
