# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0007_auto_20180201_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='application_time',
            field=models.DateTimeField(db_index=True, verbose_name='\u7533\u8bf7\u65f6\u95f4'),
        ),
    ]
