# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-02 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0008_auto_20180201_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFeature',
            fields=[
                ('model_feature_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
                ('created_time', models.BigIntegerField()),
            ],
            options={
                'db_table': 'model_feature',
                'managed': False,
            },
        ),
    ]
