# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0009_modelfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='application_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfoforstatistics',
            name='create_time',
            field=models.IntegerField(),
        ),
    ]
