# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-08 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0010_auto_20180208_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfoforstatistics',
            name='source',
            field=models.CharField(default='', max_length=64, validators='\u8d44\u4ea7\u5305\u6807\u7b7e'),
        ),
    ]
